ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "sequence" INTEGER;
ALTER TABLE "WorkOrder" ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE "WorkOrder" ADD COLUMN IF NOT EXISTS "sequence" INTEGER;

CREATE UNIQUE INDEX IF NOT EXISTS "Quote_code_key" ON "Quote"("code");
CREATE UNIQUE INDEX IF NOT EXISTS "WorkOrder_code_key" ON "WorkOrder"("code");
